sudo: required
dist: trusty
language: cpp
compiler: gcc
addons:
  apt:
    packages:
    - cmake
    - lua5.2
    - libjson-c-dev
    - liblua5.2-dev
before_install:
- wget https://github.com/fynnh/libubox/releases/download/untagged-2f3d0fb32fe4d665624f/ubox-1.0-Linux.deb
- sudo dpkg -i ubox-1.0-Linux.deb
script:
- cmake . -DBUILD_LUA=OFF
- make -j1
- make package
deploy:
  provider: releases
  api_key:
    secure: TkIxb7LiWHKdEjEGsC0IEon6Mdo4zun6/tK6WgdnkIoDXIIapMd/JF3tRsQgYMAatSlmoLmB6rVgt3mQGJHxR9tomLoyhwc3llkEJAfBXGnHnrsnjcDDUj0xQXfl0VNAI8n+VCBfyzoYRViKKaLphI+t3xMeJk4n09/+LntECy623cNCenSXOBYqKefEvlLlAt78p/dtnwGF+QP1JnQ6cpdzZYM0hAR9i5QPU7qLTygZAfNBE3D73zUJXvbvhx2ut3bIBcYEPtouU87oELC5pLWQrAKUywmFpllz09/2sM24YkBXrwbFzxHMqQJdeQlK1yqkOd1ndMwBCp9hUU8FvzAf/VD4Q+SFfXenl7w4HKDOTS17EBqRS/8oc2agbnKNdBokbuA0wWjs54udyEhK+E9iob6IeZ2Dqld2/tPJUKxncTSYwBji6f5E4c/bl8+kNoY3p1WwbRGNA6EiLQvfKe1UrztXczvUxvZndrWVkQe5CTLrFfwvhgmX1+GJIdNidjjM9YZW1lo0WYCbqKWxW1bt9PVDXBjq1HvspuPActh3Q63My9UNbBxnSLW9tvvzs2n0m3YBQLudLl/bQ8dzuWDcdkij67BUY97j2oWXev/Si50qdGCLrZHZdPoanbRX9f6FwzAfJSK4yAgvB0KUDrEUDBvpLneg4gSQxswmyF0=
  file: uci-1.0-Linux.deb
  skip_cleanup: true
  on:
    all_branches: true
